kind: Service
apiVersion: v1
metadata:
  name: zipkin-ms-3
spec:
  selector:
    app: zipkin-ms-3
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
  type: ClusterIP
