apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-ms-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-ms-1
  template:
    metadata:
      labels:
        app: zipkin-ms-1
    spec:
      containers:
        - name: zipkin-ms-1
          image: zipkin-lab/zipkin-ms-1:v1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          env:
            - name: ZIPKIN_MS_2_URI
              value: http://zipkin-ms-2.default.svc.cluster.local:8080
